### ISSUE TITLE
java.lang.NoClassDefFoundError: org.gradle.api.internal.file.copy.CopySpecImpl

### ISSUE THREAD

**Issue by jdneo** [microsoft/build-server-for-gradle#190]
```
Caused by: java.lang.NoClassDefFoundError: org.gradle.api.internal.file.copy.CopySpecImpl
	at com.trigonic.gradle.plugins.rpm.RpmPlugin.class$(RpmPlugin.groovy)
	at com.trigonic.gradle.plugins.rpm.RpmPlugin.$get$$class$org$gradle$api$internal$file$copy$CopySpecImpl(RpmPlugin.groovy)
	at com.trigonic.gradle.plugins.rpm.RpmPlugin.apply(RpmPlugin.groovy:34)
	at com.trigonic.gradle.plugins.rpm.RpmPlugin.apply(RpmPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:190)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:285)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:148)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:161)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:43)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:98)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:184)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:37)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_6qmpmgvrqkfckjn21q7dabzl6.run(<REDACTED: user-file-path>:1)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 172 more
```

```
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.internal.file.copy.DefaultCopySpec(org.gradle.api.internal.file.DefaultFileCollectionFactory, org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator, org.gradle.api.tasks.util.internal.PatternSets$PatternSetFactory)
	at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite.access$401(DefaultCallSiteDecorator.java:156)
	at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite$4.callOriginal(DefaultCallSiteDecorator.java:210)
	at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$1.doIntercept(DefaultCallSiteDecorator.java:69)
	at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite.callConstructor(DefaultCallSiteDecorator.java:207)
	at com.netflix.gradle.plugins.packaging.ProjectPackagingExtension.<init>(ProjectPackagingExtension.groovy:49)
	at com.netflix.gradle.plugins.packaging.ProjectPackagingExtension_Decorated.<init>(Unknown Source)
	at <REDACTED: user-file-path>(DirectConstructorHandleAccessor.java:62)
	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2105)
	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:528)
	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
	... 216 more
```

**Comment by jdneo** [comment]
Is this related with the project dependency resolution? @Arthurm1

**Comment by Bom123789** [comment]
> ```
> Caused by: java.lang.NoClassDefFoundError: org.gradle.api.internal.file.copy.CopySpecImpl
> 	at com.trigonic.gradle.plugins.rpm.RpmPlugin.class$(RpmPlugin.groovy)
> 	at com.trigonic.gradle.plugins.rpm.RpmPlugin.$get$$class$org$gradle$api$internal$file$copy$CopySpecImpl(RpmPlugin.groovy)
> 	at com.trigonic.gradle.plugins.rpm.RpmPlugin.apply(RpmPlugin.groovy:34)
> 	at com.trigonic.gradle.plugins.rpm.RpmPlugin.apply(RpmPlugin.groovy)
> 	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
> 	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
> 	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:190)
> 	at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)
> 	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:285)
> 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
> 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
> 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
> 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
> 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
> 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
> 	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
> 	at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
> 	at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:43)
> 	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)
> 	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:148)
> 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:161)
> 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:43)
> 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:98)
> 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:184)
> 	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)
> 	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:37)
> 	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
> 	at build_6qmpmgvrqkfckjn21q7dabzl6.run(<REDACTED: user-file-path>:1)
> 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
> 	... 172 more
> ```
> 
> ```
> Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.internal.file.copy.DefaultCopySpec(org.gradle.api.internal.file.DefaultFileCollectionFactory, org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator, org.gradle.api.tasks.util.internal.PatternSets$PatternSetFactory)
> 	at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite.access$401(DefaultCallSiteDecorator.java:156)
> 	at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite$4.callOriginal(DefaultCallSiteDecorator.java:210)
> 	at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$1.doIntercept(DefaultCallSiteDecorator.java:69)
> 	at org.gradle.internal.classpath.intercept.DefaultCallSiteDecorator$DecoratingCallSite.callConstructor(DefaultCallSiteDecorator.java:207)
> 	at com.netflix.gradle.plugins.packaging.ProjectPackagingExtension.<init>(ProjectPackagingExtension.groovy:49)
> 	at com.netflix.gradle.plugins.packaging.ProjectPackagingExtension_Decorated.<init>(Unknown Source)
> 	at <REDACTED: user-file-path>(DirectConstructorHandleAccessor.java:62)
> 	at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2105)
> 	at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:528)
> 	at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:64)
> 	... 216 more
> ```

**Comment by Arthurm1** [comment]
@Bom123789 I could never reproduce this.  I added #191 just to show that a basic Gradle project works with the Nebula plugin.

Do you have a sample project where this happens? If not then I'm at a dead end.
